[package]
name = "wpfxm"
version = "0.0.0"
authors = ["Acizza <jonathanmce@pm.me>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
dirs = "~1.0.0"
failure = "~0.1.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
toml = "~0.4.0"

[profile.release]
codegen-units = 1
lto = true